-- postgres

CREATE TABLE users (
	id BIGSERIAL PRIMARY KEY,
	username VARCHAR(50) UNIQUE NOT NULL,
	displayName VARCHAR(100) NOT NULL,
	password VARCHAR(255) NOT NULL,
	balance DECIMAL(15, 2) DEFAULT 0.00,
	createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)
