-- postgres
DROP TABLE IF EXISTS users;

CREATE TABLE users (
	id BIGSERIAL PRIMARY KEY,
	username VARCHAR(50) UNIQUE NOT NULL,
	display_name VARCHAR(100) NOT NULL,
	password VARCHAR(255) NOT NULL,
	balance DECIMAL(15, 2) DEFAULT 0.00,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)
